
$content = Get-Content -Raw -Encoding UTF8 index.html
$content = $content.Replace("OYUNA BAŞLA", "START SYSTEM")
$content = $content.Replace("DEVAM ET", "CONTINUE")
$content = $content.Replace("SATIN ALDIKLARIM", "INVENTORY LOG")
$content = $content.Replace("Henüz alım yok", "No acquisitions yet")
$content = $content.Replace("GÖREV TAMAMLANDI!", "MISSION COMPLETE!")
$content = $content.Replace("Görev Ödülü:", "Mission Bounty:")
$content = $content.Replace("KAZANILAN", "EARNED")
$content = $content.Replace("ÖĞRENİLECEK KAVRAMLAR", "CONCEPTS TO LEARN")
$content = $content.Replace("RETURN TO TERMINAL", "RETURN TO TERMINAL")
$content = $content.Replace("Maaşı Aldın!", "Salary Received!")
$content = $content.Replace("Kurumsal Prim!", "Corporate Bonus!")
$content = $content.Replace("Genel İhtiyaç Karşılandı", "Basic Needs Met")
$content = $content.Replace("Fazladan Mesai Parası", "Overtime Pay")
$content = $content.Replace("İSTATİSTİKLERİ GÖR", "VIEW TELEMETRY")
$content = $content.Replace("UNVAN KAZANILDI", "TITLE ACQUIRED")
$content = $content.Replace("Kalan Bakiye", "Remaining Credits")
$content = $content.Replace("Toplam XP", "Total XP")
$content = $content.Replace("Toplam Başarı", "Total Successes")
$content = $content.Replace("Toplam Hata", "Total Mistakes")
$content = $content.Replace("BAŞTAN BAŞLA ⟳", "REINITIALIZE ⟳")
$content = $content.Replace("EKİPMANLARIN OYUNA KATKISI", "HARDWARE SYNERGY")
[System.IO.File]::WriteAllText("index.html", $content, [System.Text.Encoding]::UTF8)

